// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_users.proto

#include "google/cloud/sqladmin/sql_users_connection.h"
#include "google/cloud/sqladmin/internal/sql_users_connection_impl.h"
#include "google/cloud/sqladmin/internal/sql_users_option_defaults.h"
#include "google/cloud/sqladmin/internal/sql_users_stub_factory.h"
#include "google/cloud/sqladmin/sql_users_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/common_options.h"
#include "google/cloud/grpc_options.h"
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

SqlUsersServiceConnection::~SqlUsersServiceConnection() = default;

StatusOr<google::cloud::sql::v1::Operation> SqlUsersServiceConnection::Delete(
    google::cloud::sql::v1::SqlUsersDeleteRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::sql::v1::Operation> SqlUsersServiceConnection::Insert(
    google::cloud::sql::v1::SqlUsersInsertRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::sql::v1::UsersListResponse>
SqlUsersServiceConnection::List(
    google::cloud::sql::v1::SqlUsersListRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

StatusOr<google::cloud::sql::v1::Operation> SqlUsersServiceConnection::Update(
    google::cloud::sql::v1::SqlUsersUpdateRequest const&) {
  return Status(StatusCode::kUnimplemented, "not implemented");
}

std::shared_ptr<SqlUsersServiceConnection> MakeSqlUsersServiceConnection(
    Options options) {
  internal::CheckExpectedOptions<CommonOptionList, GrpcOptionList,
                                 SqlUsersServicePolicyOptionList>(options,
                                                                  __func__);
  options =
      sqladmin_internal::SqlUsersServiceDefaultOptions(std::move(options));
  auto background = internal::MakeBackgroundThreadsFactory(options)();
  auto stub = sqladmin_internal::CreateDefaultSqlUsersServiceStub(
      background->cq(), options);
  return std::make_shared<sqladmin_internal::SqlUsersServiceConnectionImpl>(
      std::move(background), std::move(stub), std::move(options));
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin
}  // namespace cloud
}  // namespace google

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

std::shared_ptr<sqladmin::SqlUsersServiceConnection>
MakeSqlUsersServiceConnection(std::shared_ptr<SqlUsersServiceStub> stub,
                              Options options) {
  options = SqlUsersServiceDefaultOptions(std::move(options));
  auto background = internal::MakeBackgroundThreadsFactory(options)();
  return std::make_shared<sqladmin_internal::SqlUsersServiceConnectionImpl>(
      std::move(background), std::move(stub), std::move(options));
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google
