// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_instance_names.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_SQL_INSTANCE_NAMES_CONNECTION_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_SQL_INSTANCE_NAMES_CONNECTION_H

#include "google/cloud/sqladmin/internal/sql_instance_names_retry_traits.h"
#include "google/cloud/sqladmin/internal/sql_instance_names_stub.h"
#include "google/cloud/sqladmin/sql_instance_names_connection_idempotency_policy.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

using SqlInstanceNamesServiceRetryPolicy =
    ::google::cloud::internal::TraitBasedRetryPolicy<
        sqladmin_internal::SqlInstanceNamesServiceRetryTraits>;

using SqlInstanceNamesServiceLimitedTimeRetryPolicy =
    ::google::cloud::internal::LimitedTimeRetryPolicy<
        sqladmin_internal::SqlInstanceNamesServiceRetryTraits>;

using SqlInstanceNamesServiceLimitedErrorCountRetryPolicy =
    ::google::cloud::internal::LimitedErrorCountRetryPolicy<
        sqladmin_internal::SqlInstanceNamesServiceRetryTraits>;

class SqlInstanceNamesServiceConnection {
 public:
  virtual ~SqlInstanceNamesServiceConnection() = 0;

  virtual Options options() { return Options{}; }
};

std::shared_ptr<SqlInstanceNamesServiceConnection>
MakeSqlInstanceNamesServiceConnection(Options options = {});

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin
}  // namespace cloud
}  // namespace google

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

std::shared_ptr<sqladmin::SqlInstanceNamesServiceConnection>
MakeSqlInstanceNamesServiceConnection(
    std::shared_ptr<SqlInstanceNamesServiceStub> stub, Options options);

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_SQL_INSTANCE_NAMES_CONNECTION_H
