// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_instances.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_SQL_INSTANCES_CONNECTION_IDEMPOTENCY_POLICY_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_SQL_INSTANCES_CONNECTION_IDEMPOTENCY_POLICY_H

#include "google/cloud/idempotency.h"
#include "google/cloud/internal/retry_policy.h"
#include "google/cloud/version.h"
#include <google/cloud/sql/v1/cloud_sql_instances.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class SqlInstancesServiceConnectionIdempotencyPolicy {
 public:
  virtual ~SqlInstancesServiceConnectionIdempotencyPolicy() = 0;

  /// Create a new copy of this object.
  virtual std::unique_ptr<SqlInstancesServiceConnectionIdempotencyPolicy>
  clone() const = 0;

  virtual google::cloud::Idempotency AddServerCa(
      google::cloud::sql::v1::SqlInstancesAddServerCaRequest const&
          request) = 0;

  virtual google::cloud::Idempotency Clone(
      google::cloud::sql::v1::SqlInstancesCloneRequest const& request) = 0;

  virtual google::cloud::Idempotency Delete(
      google::cloud::sql::v1::SqlInstancesDeleteRequest const& request) = 0;

  virtual google::cloud::Idempotency DemoteMaster(
      google::cloud::sql::v1::SqlInstancesDemoteMasterRequest const&
          request) = 0;

  virtual google::cloud::Idempotency Export(
      google::cloud::sql::v1::SqlInstancesExportRequest const& request) = 0;

  virtual google::cloud::Idempotency Failover(
      google::cloud::sql::v1::SqlInstancesFailoverRequest const& request) = 0;

  virtual google::cloud::Idempotency Get(
      google::cloud::sql::v1::SqlInstancesGetRequest const& request) = 0;

  virtual google::cloud::Idempotency Import(
      google::cloud::sql::v1::SqlInstancesImportRequest const& request) = 0;

  virtual google::cloud::Idempotency Insert(
      google::cloud::sql::v1::SqlInstancesInsertRequest const& request) = 0;

  virtual google::cloud::Idempotency List(
      google::cloud::sql::v1::SqlInstancesListRequest const& request) = 0;

  virtual google::cloud::Idempotency ListServerCas(
      google::cloud::sql::v1::SqlInstancesListServerCasRequest const&
          request) = 0;

  virtual google::cloud::Idempotency Patch(
      google::cloud::sql::v1::SqlInstancesPatchRequest const& request) = 0;

  virtual google::cloud::Idempotency PromoteReplica(
      google::cloud::sql::v1::SqlInstancesPromoteReplicaRequest const&
          request) = 0;

  virtual google::cloud::Idempotency ResetSslConfig(
      google::cloud::sql::v1::SqlInstancesResetSslConfigRequest const&
          request) = 0;

  virtual google::cloud::Idempotency Restart(
      google::cloud::sql::v1::SqlInstancesRestartRequest const& request) = 0;

  virtual google::cloud::Idempotency RestoreBackup(
      google::cloud::sql::v1::SqlInstancesRestoreBackupRequest const&
          request) = 0;

  virtual google::cloud::Idempotency RotateServerCa(
      google::cloud::sql::v1::SqlInstancesRotateServerCaRequest const&
          request) = 0;

  virtual google::cloud::Idempotency StartReplica(
      google::cloud::sql::v1::SqlInstancesStartReplicaRequest const&
          request) = 0;

  virtual google::cloud::Idempotency StopReplica(
      google::cloud::sql::v1::SqlInstancesStopReplicaRequest const&
          request) = 0;

  virtual google::cloud::Idempotency TruncateLog(
      google::cloud::sql::v1::SqlInstancesTruncateLogRequest const&
          request) = 0;

  virtual google::cloud::Idempotency Update(
      google::cloud::sql::v1::SqlInstancesUpdateRequest const& request) = 0;

  virtual google::cloud::Idempotency CreateEphemeral(
      google::cloud::sql::v1::SqlInstancesCreateEphemeralCertRequest const&
          request) = 0;

  virtual google::cloud::Idempotency RescheduleMaintenance(
      google::cloud::sql::v1::SqlInstancesRescheduleMaintenanceRequest const&
          request) = 0;

  virtual google::cloud::Idempotency VerifyExternalSyncSettings(
      google::cloud::sql::v1::
          SqlInstancesVerifyExternalSyncSettingsRequest const& request) = 0;

  virtual google::cloud::Idempotency StartExternalSync(
      google::cloud::sql::v1::SqlInstancesStartExternalSyncRequest const&
          request) = 0;
};

std::unique_ptr<SqlInstancesServiceConnectionIdempotencyPolicy>
MakeDefaultSqlInstancesServiceConnectionIdempotencyPolicy();

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_SQL_INSTANCES_CONNECTION_IDEMPOTENCY_POLICY_H
