// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_flags.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_FLAGS_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_FLAGS_CONNECTION_IMPL_H

#include "google/cloud/sqladmin/internal/sql_flags_retry_traits.h"
#include "google/cloud/sqladmin/internal/sql_flags_stub.h"
#include "google/cloud/sqladmin/sql_flags_connection.h"
#include "google/cloud/sqladmin/sql_flags_connection_idempotency_policy.h"
#include "google/cloud/sqladmin/sql_flags_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class SqlFlagsServiceConnectionImpl
    : public sqladmin::SqlFlagsServiceConnection {
 public:
  ~SqlFlagsServiceConnectionImpl() override = default;

  SqlFlagsServiceConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<sqladmin_internal::SqlFlagsServiceStub> stub,
      Options options);

  Options options() override { return options_; }

  StatusOr<google::cloud::sql::v1::FlagsListResponse> List(
      google::cloud::sql::v1::SqlFlagsListRequest const& request) override;

 private:
  std::unique_ptr<sqladmin::SqlFlagsServiceRetryPolicy> retry_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<sqladmin::SqlFlagsServiceRetryPolicyOption>()) {
      return options.get<sqladmin::SqlFlagsServiceRetryPolicyOption>()->clone();
    }
    return options_.get<sqladmin::SqlFlagsServiceRetryPolicyOption>()->clone();
  }

  std::unique_ptr<BackoffPolicy> backoff_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<sqladmin::SqlFlagsServiceBackoffPolicyOption>()) {
      return options.get<sqladmin::SqlFlagsServiceBackoffPolicyOption>()
          ->clone();
    }
    return options_.get<sqladmin::SqlFlagsServiceBackoffPolicyOption>()
        ->clone();
  }

  std::unique_ptr<sqladmin::SqlFlagsServiceConnectionIdempotencyPolicy>
  idempotency_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<
            sqladmin::SqlFlagsServiceConnectionIdempotencyPolicyOption>()) {
      return options
          .get<sqladmin::SqlFlagsServiceConnectionIdempotencyPolicyOption>()
          ->clone();
    }
    return options_
        .get<sqladmin::SqlFlagsServiceConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<sqladmin_internal::SqlFlagsServiceStub> stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_FLAGS_CONNECTION_IMPL_H
