// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_ssl_certs.proto

#include "google/cloud/sqladmin/internal/sql_ssl_certs_stub.h"
#include "google/cloud/grpc_error_delegate.h"
#include "google/cloud/status_or.h"
#include <google/cloud/sql/v1/cloud_sql_ssl_certs.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

SqlSslCertsServiceStub::~SqlSslCertsServiceStub() = default;

StatusOr<google::cloud::sql::v1::Operation>
DefaultSqlSslCertsServiceStub::Delete(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlSslCertsDeleteRequest const& request) {
  google::cloud::sql::v1::Operation response;
  auto status = grpc_stub_->Delete(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::sql::v1::SslCert> DefaultSqlSslCertsServiceStub::Get(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlSslCertsGetRequest const& request) {
  google::cloud::sql::v1::SslCert response;
  auto status = grpc_stub_->Get(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::sql::v1::SslCertsInsertResponse>
DefaultSqlSslCertsServiceStub::Insert(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlSslCertsInsertRequest const& request) {
  google::cloud::sql::v1::SslCertsInsertResponse response;
  auto status = grpc_stub_->Insert(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::sql::v1::SslCertsListResponse>
DefaultSqlSslCertsServiceStub::List(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlSslCertsListRequest const& request) {
  google::cloud::sql::v1::SslCertsListResponse response;
  auto status = grpc_stub_->List(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google
