// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_instances.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_INSTANCES_STUB_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_INSTANCES_STUB_H

#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <google/cloud/sql/v1/cloud_sql_instances.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class SqlInstancesServiceStub {
 public:
  virtual ~SqlInstancesServiceStub() = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> AddServerCa(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesAddServerCaRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Clone(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesCloneRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Delete(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesDeleteRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> DemoteMaster(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesDemoteMasterRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Export(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesExportRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Failover(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesFailoverRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::DatabaseInstance> Get(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesGetRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Import(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesImportRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Insert(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesInsertRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::InstancesListResponse> List(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesListRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::InstancesListServerCasResponse>
  ListServerCas(grpc::ClientContext& context,
                google::cloud::sql::v1::SqlInstancesListServerCasRequest const&
                    request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Patch(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesPatchRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> PromoteReplica(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesPromoteReplicaRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> ResetSslConfig(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesResetSslConfigRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Restart(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesRestartRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> RestoreBackup(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesRestoreBackupRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> RotateServerCa(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesRotateServerCaRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> StartReplica(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesStartReplicaRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> StopReplica(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesStopReplicaRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> TruncateLog(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesTruncateLogRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> Update(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesUpdateRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::SslCert> CreateEphemeral(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesCreateEphemeralCertRequest const&
          request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> RescheduleMaintenance(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesRescheduleMaintenanceRequest const&
          request) = 0;

  virtual StatusOr<
      google::cloud::sql::v1::SqlInstancesVerifyExternalSyncSettingsResponse>
  VerifyExternalSyncSettings(
      grpc::ClientContext& context,
      google::cloud::sql::v1::
          SqlInstancesVerifyExternalSyncSettingsRequest const& request) = 0;

  virtual StatusOr<google::cloud::sql::v1::Operation> StartExternalSync(
      grpc::ClientContext& context,
      google::cloud::sql::v1::SqlInstancesStartExternalSyncRequest const&
          request) = 0;
};

class DefaultSqlInstancesServiceStub : public SqlInstancesServiceStub {
 public:
  explicit DefaultSqlInstancesServiceStub(
      std::unique_ptr<
          google::cloud::sql::v1::SqlInstancesService::StubInterface>
          grpc_stub)
      : grpc_stub_(std::move(grpc_stub)) {}

  StatusOr<google::cloud::sql::v1::Operation> AddServerCa(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesAddServerCaRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> Clone(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesCloneRequest const& request) override;

  StatusOr<google::cloud::sql::v1::Operation> Delete(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesDeleteRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> DemoteMaster(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesDemoteMasterRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> Export(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesExportRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> Failover(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesFailoverRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::DatabaseInstance> Get(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesGetRequest const& request) override;

  StatusOr<google::cloud::sql::v1::Operation> Import(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesImportRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> Insert(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesInsertRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::InstancesListResponse> List(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesListRequest const& request) override;

  StatusOr<google::cloud::sql::v1::InstancesListServerCasResponse>
  ListServerCas(grpc::ClientContext& client_context,
                google::cloud::sql::v1::SqlInstancesListServerCasRequest const&
                    request) override;

  StatusOr<google::cloud::sql::v1::Operation> Patch(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesPatchRequest const& request) override;

  StatusOr<google::cloud::sql::v1::Operation> PromoteReplica(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesPromoteReplicaRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> ResetSslConfig(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesResetSslConfigRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> Restart(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesRestartRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> RestoreBackup(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesRestoreBackupRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> RotateServerCa(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesRotateServerCaRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> StartReplica(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesStartReplicaRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> StopReplica(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesStopReplicaRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> TruncateLog(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesTruncateLogRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> Update(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesUpdateRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::SslCert> CreateEphemeral(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesCreateEphemeralCertRequest const&
          request) override;

  StatusOr<google::cloud::sql::v1::Operation> RescheduleMaintenance(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesRescheduleMaintenanceRequest const&
          request) override;

  StatusOr<
      google::cloud::sql::v1::SqlInstancesVerifyExternalSyncSettingsResponse>
  VerifyExternalSyncSettings(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::
          SqlInstancesVerifyExternalSyncSettingsRequest const& request)
      override;

  StatusOr<google::cloud::sql::v1::Operation> StartExternalSync(
      grpc::ClientContext& client_context,
      google::cloud::sql::v1::SqlInstancesStartExternalSyncRequest const&
          request) override;

 private:
  std::unique_ptr<google::cloud::sql::v1::SqlInstancesService::StubInterface>
      grpc_stub_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_INSTANCES_STUB_H
