// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_backup_runs.proto

#include "google/cloud/sqladmin/internal/sql_backup_runs_stub.h"
#include "google/cloud/grpc_error_delegate.h"
#include "google/cloud/status_or.h"
#include <google/cloud/sql/v1/cloud_sql_backup_runs.grpc.pb.h>
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

SqlBackupRunsServiceStub::~SqlBackupRunsServiceStub() = default;

StatusOr<google::cloud::sql::v1::Operation>
DefaultSqlBackupRunsServiceStub::Delete(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlBackupRunsDeleteRequest const& request) {
  google::cloud::sql::v1::Operation response;
  auto status = grpc_stub_->Delete(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::sql::v1::BackupRun>
DefaultSqlBackupRunsServiceStub::Get(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlBackupRunsGetRequest const& request) {
  google::cloud::sql::v1::BackupRun response;
  auto status = grpc_stub_->Get(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::sql::v1::Operation>
DefaultSqlBackupRunsServiceStub::Insert(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlBackupRunsInsertRequest const& request) {
  google::cloud::sql::v1::Operation response;
  auto status = grpc_stub_->Insert(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

StatusOr<google::cloud::sql::v1::BackupRunsListResponse>
DefaultSqlBackupRunsServiceStub::List(
    grpc::ClientContext& client_context,
    google::cloud::sql::v1::SqlBackupRunsListRequest const& request) {
  google::cloud::sql::v1::BackupRunsListResponse response;
  auto status = grpc_stub_->List(&client_context, request, &response);
  if (!status.ok()) {
    return google::cloud::MakeStatusFromRpcError(status);
  }
  return response;
}

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google
