// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by the Codegen C++ plugin.
// If you make any local changes, they will be lost.
// source: google/cloud/sql/v1/cloud_sql_tiers.proto

#ifndef GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_TIERS_CONNECTION_IMPL_H
#define GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_TIERS_CONNECTION_IMPL_H

#include "google/cloud/sqladmin/internal/sql_tiers_retry_traits.h"
#include "google/cloud/sqladmin/internal/sql_tiers_stub.h"
#include "google/cloud/sqladmin/sql_tiers_connection.h"
#include "google/cloud/sqladmin/sql_tiers_connection_idempotency_policy.h"
#include "google/cloud/sqladmin/sql_tiers_options.h"
#include "google/cloud/background_threads.h"
#include "google/cloud/backoff_policy.h"
#include "google/cloud/options.h"
#include "google/cloud/status_or.h"
#include "google/cloud/version.h"
#include <memory>

namespace google {
namespace cloud {
namespace sqladmin_internal {
GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_BEGIN

class SqlTiersServiceConnectionImpl
    : public sqladmin::SqlTiersServiceConnection {
 public:
  ~SqlTiersServiceConnectionImpl() override = default;

  SqlTiersServiceConnectionImpl(
      std::unique_ptr<google::cloud::BackgroundThreads> background,
      std::shared_ptr<sqladmin_internal::SqlTiersServiceStub> stub,
      Options options);

  Options options() override { return options_; }

  StatusOr<google::cloud::sql::v1::TiersListResponse> List(
      google::cloud::sql::v1::SqlTiersListRequest const& request) override;

 private:
  std::unique_ptr<sqladmin::SqlTiersServiceRetryPolicy> retry_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<sqladmin::SqlTiersServiceRetryPolicyOption>()) {
      return options.get<sqladmin::SqlTiersServiceRetryPolicyOption>()->clone();
    }
    return options_.get<sqladmin::SqlTiersServiceRetryPolicyOption>()->clone();
  }

  std::unique_ptr<BackoffPolicy> backoff_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<sqladmin::SqlTiersServiceBackoffPolicyOption>()) {
      return options.get<sqladmin::SqlTiersServiceBackoffPolicyOption>()
          ->clone();
    }
    return options_.get<sqladmin::SqlTiersServiceBackoffPolicyOption>()
        ->clone();
  }

  std::unique_ptr<sqladmin::SqlTiersServiceConnectionIdempotencyPolicy>
  idempotency_policy() {
    auto const& options = internal::CurrentOptions();
    if (options.has<
            sqladmin::SqlTiersServiceConnectionIdempotencyPolicyOption>()) {
      return options
          .get<sqladmin::SqlTiersServiceConnectionIdempotencyPolicyOption>()
          ->clone();
    }
    return options_
        .get<sqladmin::SqlTiersServiceConnectionIdempotencyPolicyOption>()
        ->clone();
  }

  std::unique_ptr<google::cloud::BackgroundThreads> background_;
  std::shared_ptr<sqladmin_internal::SqlTiersServiceStub> stub_;
  Options options_;
};

GOOGLE_CLOUD_CPP_INLINE_NAMESPACE_END
}  // namespace sqladmin_internal
}  // namespace cloud
}  // namespace google

#endif  // GOOGLE_CLOUD_CPP_GOOGLE_CLOUD_SQLADMIN_INTERNAL_SQL_TIERS_CONNECTION_IMPL_H
